blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BlogBundle:Default:index }

BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+

BloggerBlogBundle_sidebar:
    pattern:  /sidebar
    defaults: { _controller: BlogBundle:Page:sidebar }
    requirements:
        _method:  GET